### ISSUE TITLE
Some preparation for going public is needed

### ISSUE THREAD

**Issue by jokochems** [pommes-public/pommesdispatch#1]
When finally going public, I'd find it nice to have a complete package, i.e.:
- [x] a clean code base and repo, one might clone or fork @jokochems, @yannickwerner
- [x] a usage description for the packages @jokochems, @yannickwerner  
- [x] a Sphinx documentation @jokochems 
- [ ] a catchy and funny logo -> I have something in mind

We can discuss about contents, timelines and responsibilities in upcoming meetings.

**Comment by hannesfelipe** [comment]
After you told the idea last week: I'd like to see the fries logo :D

**Comment by jokochems** [comment]
- I'm currently working on the docs and usage description it includes. I'm having some troubles with relative importing.
- For the logo, I think it could become tough to find something appropriate and for free use. Instead, one could have somebody design it.

**Comment by jokochems** [comment]
> 
> 
> After you told the idea last week: I'd like to see the fries logo :D

Do you know someone who could help with the design? I'm not great with fancy visualizations.

**Comment by jokochems** [comment]
When the PyPI upload succeeds, the logo + the pommesdata updates are the only remaining things to keep us from going public.

**Comment by jokochems** [comment]
> 
> 
> When the PyPI upload succeeds, the logo + the pommesdata updates are the only remaining things to keep us from going public.

Uploading to testPyPI was successful. I can't really imagine why it shouldn't be for PyPI. Now we only need the logo + the changes in pommesdata to go public.

**Comment by yannickwerner** [comment]
What about including PEP8 checker etc. like Black, Flake8?

**Comment by jokochems** [comment]
> What about including PEP8 checker etc. like Black, Flake8?

I think, this is already included. You can run black from console or configure your IDE to use it as an external tool. See here for PyCharm: https://black.readthedocs.io/en/stable/integrations/editors.html

**Comment by jokochems** [comment]
I'll close this one for now. We can discuss about a logo in another dedicated issue. Since `pommesdispatch` is already open, this one has become outdated.
